front:
    image: nginx
    ports:
        - "80:80"
    links:
        - "engine:engine"
    volumes:
        - ".:/home/docker:ro"
        - "./app/Resources/docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"

engine:
    build: ./app/Resources/docker/engine/
    volumes:
        - ".:/home/docker:rw"
        - "./app/Resources/docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    links:
        - "db:db"
    working_dir: "/home/docker"
    volumes_from:
        - data

db:
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
data:
    image: busybox
    volumes:
        - "./var/cache:/home/docker/var/cache:rw"
        - "./var/logs:/home/docker/var/logs:rw"
